"use client";

import { useCallback, useEffect, useState } from "react";

type Item = Record<string, unknown>;
type MasterProfile = {version:string;career:{candidate:Item;contact:Item;career_summary:Item;employment:Item[];education:Item[];training_and_certifications:Item[];projects:Item[]};skills:Record<string,Item[]>;technologies:Record<string,Item[]>;evidence:Item[]};
const MONTHS=["January","February","March","April","May","June","July","August","September","October","November","December"];
const words=(value:string)=>value.replaceAll("_"," ").split(" ").map(word=>word.toLowerCase()==="ai"?"AI":word.replace(/^\w/,letter=>letter.toUpperCase())).join(" ");
const string=(value:unknown)=>typeof value==="string"?value:"";
const list=(value:unknown)=>Array.isArray(value)?value.filter(item=>typeof item==="string") as string[]:[];
const formatDate=(value:unknown)=>{const raw=string(value).trim();const match=/^(\d{4})-(\d{2})$/.exec(raw);if(match){const index=Number(match[2])-1;if(index>=0&&index<12)return `${MONTHS[index]} ${match[1]}`;}return raw;};
const dates=(value:unknown)=>{const item=(value||{}) as Item;return [formatDate(item.start),formatDate(item.end)].filter(Boolean).join(" – ");};
const groups=(value:Record<string,Item[]>)=>Object.entries(value).filter(([,items])=>items.length>0);
const recencyKey=(item:Item)=>{const d=item.dates as Item|undefined;if(d)return string(d.end)||string(d.start);return string(item.completion);};
const sortRecentFirst=(items:Item[])=>[...items].sort((a,b)=>recencyKey(b).localeCompare(recencyKey(a)));

export function MasterResume(){
  const [profile,setProfile]=useState<MasterProfile|null>(null),[error,setError]=useState("");
  const load=useCallback(()=>fetch("http://localhost:8787/api/profile/master").then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);setProfile(value);}).catch(value=>setError(value instanceof Error?value.message:"Career profile could not be loaded.")),[]);
  useEffect(()=>{void load();const changed=()=>void load();window.addEventListener("jobs-changed",changed);return()=>window.removeEventListener("jobs-changed",changed);},[load]);
  if(!profile)return <section className="master-resume loading"><p>{error||"Loading your verified career profile…"}</p></section>;
  const {career}=profile, candidate=career.candidate, contact=career.contact, summary=career.career_summary;
  return <section className="master-resume">
    <header><div><p className="eyebrow">MASTER RESUME</p><h1>{string(candidate.name)}</h1><p>{string(summary.positioning)}</p><small>{[contact.location,contact.email,contact.phone,contact.linkedin].filter(Boolean).join(" · ")}</small></div><div className="master-resume-downloads"><a className="download-master-resume" href="http://localhost:8787/api/profile/master-resume.pdf">Download PDF</a><a className="download-master-resume" href="http://localhost:8787/api/profile/master-resume.docx">Download DOCX</a></div></header>
    <nav className="profile-section-nav" aria-label="Master resume sections"><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a href="#technologies">Technologies</a><a href="#education">Education</a><a href="#certifications">Certifications</a><a href="#evidence">Evidence</a></nav>
    <section id="experience" className="master-section"><div className="master-section-title"><span>01</span><div><p className="eyebrow">CAREER HISTORY</p><h2>Work experience</h2></div></div><div className="experience-timeline">{career.employment.map(role=><article key={string(role.id)}><span className="timeline-dot"/><div className="role-heading"><div><h3>{string(role.official_title)}</h3><strong>{string(role.organization)}</strong></div><span>{dates(role.dates)}</span></div><small>{[role.location,role.engagement_type].filter(Boolean).join(" · ")}</small><p>{string(role.summary)}</p>{list(role.accomplishments).length>0&&<ul>{list(role.accomplishments).map(item=><li key={item}>{item}</li>)}</ul>}{list(role.duties).length>0&&<div className="role-duties"><small>Duties</small><ul>{list(role.duties).map(item=><li key={item}>{item}</li>)}</ul></div>}</article>)}</div></section>
    <section id="projects" className="master-section"><div className="master-section-title"><span>02</span><div><p className="eyebrow">SELECTED WORK</p><h2>Projects</h2></div></div><div className="master-card-grid">{career.projects.map(project=><article className={project.id==="ai_job_search_agent"?"flagship-project":undefined} key={string(project.id)}><span>{string(project.type)}</span><h3>{string(project.name)}</h3><small>{[project.role,project.organization,project.status,dates(project.dates)].filter(Boolean).join(" · ")}</small><p>{string(project.summary)}</p>{string(project.url)&&<p><a href={string(project.url)} target="_blank" rel="noreferrer">{string(project.url)}</a></p>}{list(project.highlights).length>0&&<ul>{list(project.highlights).map(item=><li key={item}>{item}</li>)}</ul>}</article>)}</div></section>
    <section id="skills" className="master-section"><div className="master-section-title"><span>03</span><div><p className="eyebrow">VERIFIED CAPABILITIES</p><h2>Skills</h2></div></div><div className="inventory-groups">{groups(profile.skills).map(([group,items])=><article key={group}><h3>{words(group)}</h3><div>{items.map(item=><span key={string(item.id)}>{string(item.name)}<small>{string(item.proficiency)}</small></span>)}</div></article>)}</div></section>
    <section id="technologies" className="master-section"><div className="master-section-title"><span>04</span><div><p className="eyebrow">TOOLS & PLATFORMS</p><h2>Technologies</h2></div></div><div className="inventory-groups">{groups(profile.technologies).map(([group,items])=><article key={group}><h3>{words(group)}</h3><div>{items.map(item=><span key={string(item.id)}>{string(item.name)}<small>{string(item.level)}</small></span>)}</div></article>)}</div></section>
    <section id="education" className="master-section"><div className="master-section-title"><span>05</span><div><p className="eyebrow">EDUCATION</p><h2>Education</h2></div></div><div className="credential-list">{sortRecentFirst(career.education).map(item=><article key={string(item.id)}><h3>{string(item.credential)} · {string(item.field)}</h3><p>{string(item.institution)} · {string(item.location)}</p><span>{dates(item.dates)}</span></article>)}</div></section>
    <section id="certifications" className="master-section"><div className="master-section-title"><span>06</span><div><p className="eyebrow">TRAINING</p><h2>Certifications</h2></div></div><div className="credential-list">{sortRecentFirst(career.training_and_certifications).map(item=><article key={string(item.id)}><h3>{string(item.name)}</h3><p>{[string(item.provider),string(item.location),string(item.note)].filter(Boolean).join(" · ")}</p><span>{item.dates?dates(item.dates):formatDate(item.completion)}</span></article>)}</div></section>
    <section id="evidence" className="master-section"><div className="master-section-title"><span>07</span><div><p className="eyebrow">DEFENSIBLE ACCOMPLISHMENTS</p><h2>Evidence library</h2></div></div><div className="evidence-grid">{profile.evidence.map(item=><article key={string(item.id)}><span>{string(item.type)}</span><h3>{string(item.title)}</h3><p>{string(item.context)}</p>{list(item.outcomes).length>0&&<ul>{list(item.outcomes).map(outcome=><li key={outcome}>{outcome}</li>)}</ul>}<small>Confidence: {string(item.confidence)}</small></article>)}</div></section>
  </section>;
}
