"use client";

import { useEffect, useState } from "react";

type Gmail = { connected: boolean; email: string; poll_minutes: number };

export function AlertInbox({ expanded = false }: { expanded?: boolean }) {
  const [source, setSource] = useState("linkedin"), [content, setContent] = useState(""), [message, setMessage] = useState(""), [working, setWorking] = useState(false), [appPassword, setAppPassword] = useState("");
  const [gmail, setGmail] = useState<Gmail>({ connected: false, email: "", poll_minutes: 10 });
  useEffect(() => { fetch("http://localhost:8787/api/gmail-alerts").then((response) => response.ok ? response.json() : gmail).then(setGmail).catch(() => undefined); }, []);
  async function importAlert() { setWorking(true); setMessage(""); try { const response = await fetch("http://localhost:8787/api/job-alerts/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source, content }) }); const value = await response.json(); if (!response.ok) throw new Error(value.error || "Alert could not be imported."); setContent(""); setMessage(`${value.added} new job${value.added === 1 ? "" : "s"} added to the unified workspace.`); window.dispatchEvent(new Event("jobs-changed")); } catch (error) { setMessage(error instanceof Error ? error.message : "Alert could not be imported."); } finally { setWorking(false); } }
  async function gmailAction(action: "connect" | "check") { setWorking(true); setMessage(""); try { const response = await fetch(`http://localhost:8787/api/gmail-alerts/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: action === "connect" ? JSON.stringify({ email: gmail.email, app_password: appPassword, poll_minutes: gmail.poll_minutes }) : "{}" }); const value = await response.json(); if (!response.ok) throw new Error(value.error); if (action === "connect") { setGmail(value); setAppPassword(""); } setMessage(`Sources checked. ${value.result?.jobs_added ?? value.jobs_added ?? 0} new jobs added.`); window.dispatchEvent(new Event("jobs-changed")); } catch (error) { setMessage(error instanceof Error ? error.message : "Gmail could not be checked."); } finally { setWorking(false); } }
  async function readFile(file?: File) { if (file) setContent(await file.text()); }
  return <details className="job-source-panel" id="job-sources" open={expanded}><summary><div><span>JOB INTAKE</span><strong>Email alerts and saved alert emails</strong></div><b>{gmail.connected ? "Email alerts connected" : "Setup required"}</b></summary><div className="job-source-content"><div className="source-method-heading"><span>1</span><div><strong>Email job alerts</strong><p>Automatically collect jobs from alert emails delivered to Gmail.</p></div></div><div className="gmail-connection"><div><strong>{gmail.connected ? gmail.email : "Connect your Gmail alert inbox"}</strong><p>{gmail.connected ? `Checking every ${gmail.poll_minutes} minutes without marking messages as read.` : "Use a dedicated Google app password. Your normal password is never requested."}</p></div>{gmail.connected ? <button onClick={() => gmailAction("check")} disabled={working}>Check for new jobs</button> : <div className="gmail-fields"><input aria-label="Gmail address" type="email" value={gmail.email} onChange={(event) => setGmail({ ...gmail, email: event.target.value })} placeholder="you@gmail.com" /><input aria-label="Gmail app password" type="password" value={appPassword} onChange={(event) => setAppPassword(event.target.value)} placeholder="16-character app password" /><button onClick={() => gmailAction("connect")} disabled={working || !gmail.email || !appPassword}>Connect email alerts</button></div>}</div><div className="source-method-heading"><span>2</span><div><strong>Import jobs from an alert email</strong><p>Upload or paste a saved LinkedIn, Indeed, or Eluta alert email.</p></div></div><div className="alert-import"><div className="alert-fields"><label><strong>Job board</strong><select value={source} onChange={(event) => setSource(event.target.value)}><option value="linkedin">LinkedIn</option><option value="indeed">Indeed</option><option value="eluta">Eluta</option></select></label><label><strong>Saved alert email</strong><input type="file" accept=".eml,.html,.htm,.txt" onChange={(event) => readFile(event.target.files?.[0])} /></label></div><textarea aria-label="Paste alert email" value={content} onChange={(event) => setContent(event.target.value)} rows={6} placeholder="Paste the complete alert email here…" /><div className="alert-import-footer"><p role="status">{message || "Imported jobs will appear in the Jobs workspace."}</p><button disabled={working || !content.trim()} onClick={importAlert}>{working ? "Importing…" : "Add jobs from email"}</button></div></div></div></details>;
}
