"use client";

import { useEffect, useState } from "react";

type AlertJob = { id: string; source: string; title: string; posting_url: string; status: string; received_at: string };

export function AlertInbox() {
  const [source, setSource] = useState("linkedin"), [content, setContent] = useState(""), [jobs, setJobs] = useState<AlertJob[]>([]);
  const [message, setMessage] = useState(""), [working, setWorking] = useState(false);
  useEffect(() => { fetch("http://localhost:8787/api/job-alerts").then((response) => response.ok ? response.json() : { jobs: [] }).then((value) => setJobs(value.jobs || [])).catch(() => undefined); }, []);
  async function importAlert() { setWorking(true); setMessage(""); try { const response = await fetch("http://localhost:8787/api/job-alerts/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source, content }) }); const value = await response.json(); if (!response.ok) throw new Error(value.error || "Alert could not be imported."); setJobs(value.jobs); setContent(""); setMessage(`${value.added} new job${value.added === 1 ? "" : "s"} added${value.duplicates ? ` · ${value.duplicates} already in your inbox` : ""}.`); } catch (error) { setMessage(error instanceof TypeError ? "Workflow service is offline." : error instanceof Error ? error.message : "Alert could not be imported."); } finally { setWorking(false); } }
  async function readFile(file?: File) { if (!file) return; setContent(await file.text()); }
  return <section className="alert-inbox" id="alert-inbox"><div className="section-heading"><div><p className="eyebrow">LINKEDIN · INDEED · ELUTA</p><h2>Job alert inbox</h2></div><span>{jobs.length} captured</span></div><div className="alert-import"><div className="alert-fields"><label><strong>Alert source</strong><select value={source} onChange={(event) => setSource(event.target.value)}><option value="linkedin">LinkedIn</option><option value="indeed">Indeed</option><option value="eluta">Eluta</option></select></label><label className="alert-file"><strong>Upload saved email</strong><input type="file" accept=".eml,.html,.htm,.txt,message/rfc822,text/html,text/plain" onChange={(event) => readFile(event.target.files?.[0])} /></label></div><label><strong>Or paste the alert email</strong><textarea value={content} onChange={(event) => setContent(event.target.value)} rows={5} placeholder="Paste the complete email or its HTML source here…" /></label><div className="alert-import-footer"><p role="status">{message || "Only job links are saved. Tracking links are cleaned when possible."}</p><button type="button" disabled={working || !content.trim()} onClick={importAlert}>{working ? "Importing…" : "Import jobs"}</button></div></div>{jobs.length > 0 && <div className="alert-jobs">{jobs.slice(0, 12).map((job) => <article key={job.id}><span className={`source-mark ${job.source}`}>{job.source.charAt(0).toUpperCase()}</span><div><strong>{job.title}</strong><small>{job.source} · Needs full posting capture</small></div><a href={job.posting_url} target="_blank" rel="noreferrer">Open posting</a></article>)}</div>}</section>;
}
