"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AnalyzeButton } from "./AnalyzeButton";
import { JobWorkflowPanel } from "./JobWorkflowPanel";
import { WorkflowActivity, workflowIsProcessing } from "./WorkflowActivity";

type BaseJob = { id:string; company:string; role:string; location:string|null; postingUrl:string; postedDate?:string|null; firstSeenAt?:string|null; discoveryScore:number|null; workflowStatus?:string; workflowUpdatedAt?:string|null; profileVersion?:string; analysisProfileVersion?:string|null; profileStale?:boolean };
type AnalyzedJob = BaseJob & { fitScore:number; recommendation:string; reasons:string[]; risk:string; nextAction:string };
type AlertJob = { id:string; source:string; title:string; posting_url:string; status:string; received_at:string; company?:string|null; location?:string|null; email_excerpt?:string|null; lead_id?:string|null; workflow_status?:string; captured_job?:{company:string;role:string;location?:string|null;posted_date?:string|null;first_seen_at?:string|null;discovery_score?:number|null;screening_result?:string;screening_reasons?:string[];analysis_prioritized?:boolean}; capture?:{mode:"automatic_available"|"manual_required";reason:string;status?:string;error?:string|null}; preliminary_fit?:{score:number;label:string;basis:string;limitations:string[]} };
type JobRow = BaseJob & { stage:"analyzed"|"awaiting"|"capture"; fitScore?:number; recommendation?:string; reasons?:string[]; risk?:string; nextAction?:string; source:string; leadId?:string|null; alertId?:string; captureMode?:"automatic_available"|"manual_required"; captureReason?:string; captureStatus?:string; captureServiceError?:string|null; metadataFitLabel?:string; metadataFitBasis?:string; metadataFitLimitations?:string[]; emailExcerpt?:string|null; analysisPrioritized?:boolean; screeningReasons?:string[] };

const recommendationLabel:Record<string,string> = { strong_apply:"Strong match", apply:"Apply", selective_apply:"Stretch", do_not_apply:"Do not apply" };
const sourceLabel:Record<string,string> = { linkedin:"LinkedIn", indeed:"Indeed", eluta:"Eluta", ziprecruiter:"ZipRecruiter", greenhouse:"Greenhouse", lever:"Lever" };
const workflowLabel:Record<string,string> = { capture:"Needs capture", analysis:"Analysis", decision:"Decision", strategy:"Strategy", materials:"Application materials", review_apply:"Review & apply", submitted:"Submitted & follow-up", closed:"Not applying" };

function sourceKey(value:string) { const source=value.toLowerCase().replace(/^www\./,""); if(source.includes("linkedin"))return "linkedin"; if(source.includes("indeed"))return "indeed"; if(source.includes("eluta"))return "eluta"; if(source.includes("ziprecruiter"))return "ziprecruiter"; if(source.includes("greenhouse"))return "greenhouse"; if(source.includes("lever"))return "lever"; return source; }
function workflowGroup(job:JobRow) { const status=job.workflowStatus||(job.stage==="analyzed"?"analysis_completed":"not_started"); if(job.stage==="capture")return "capture"; if(status==="application_submitted")return "submitted"; if(status==="pass")return "closed"; if(status.startsWith("strategy")||status==="pursue")return "strategy"; if(status.startsWith("resume")||status.startsWith("cover_letter")||status.startsWith("application_package"))return "materials"; if(status.startsWith("form_")||status.startsWith("application_answers")||status.startsWith("submission_"))return "review_apply"; if(["analysis_completed","decide_later"].includes(status))return "decision"; return "analysis"; }
function workflowBadgeLabel(job:JobRow) { const status=job.workflowStatus||"not_started"; if(status==="analysis_requested"||status==="analysis_running")return "Analysis running"; if(status==="analysis_failed")return "Analysis needs attention"; if(job.stage==="awaiting")return "Ready for analysis"; return workflowLabel[workflowGroup(job)]; }
function dateLabel(job:JobRow) { const value=job.postedDate||job.firstSeenAt; if(!value)return "Date unavailable"; const formatted=new Intl.DateTimeFormat("en-CA",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(value)); return job.postedDate?`Posted ${formatted}`:`First seen ${formatted}`; }

export function JobsView({ analyzedJobs, awaitingAnalysis }:{ analyzedJobs:AnalyzedJob[]; awaitingAnalysis:BaseJob[] }) {
  const [alerts,setAlerts]=useState<AlertJob[]>([]), [liveJobs,setLiveJobs]=useState<{analyzedJobs:AnalyzedJob[];awaitingAnalysis:BaseJob[]}|null>(null), [search,setSearch]=useState(""), [stage,setStage]=useState("all"), [source,setSource]=useState("all"), [fit,setFit]=useState("all"), [sort,setSort]=useState("priority"), [visible,setVisible]=useState(15), [selectedJobId,setSelectedJobId]=useState<string|null>(null), [capturingId,setCapturingId]=useState<string|null>(null), [captureError,setCaptureError]=useState<Record<string,string>>({});
  const refreshAlerts=useCallback(()=>fetch("http://localhost:8787/api/job-alerts").then(r=>r.ok?r.json():{jobs:[]}).then(v=>setAlerts(v.jobs||[])).catch(()=>undefined),[]);
  const refreshWorkflow=useCallback(()=>fetch("http://localhost:8787/api/jobs").then(r=>r.ok?r.json():null).then(value=>{if(!value)return;setLiveJobs({analyzedJobs:value.analyzedJobs||[],awaitingAnalysis:value.awaitingAnalysis||[]});}).catch(()=>undefined),[]);
  useEffect(()=>{ void refreshAlerts(); const changed=()=>void refreshAlerts(); window.addEventListener("jobs-changed",changed); const timer=window.setInterval(refreshAlerts,5000); return()=>{window.removeEventListener("jobs-changed",changed);window.clearInterval(timer);}; },[refreshAlerts]);
  useEffect(()=>{void refreshWorkflow();const changed=()=>void refreshWorkflow();window.addEventListener("jobs-changed",changed);const timer=window.setInterval(refreshWorkflow,3000);return()=>{window.removeEventListener("jobs-changed",changed);window.clearInterval(timer);};},[refreshWorkflow]);
  const jobs=useMemo<JobRow[]>(()=>{
    const currentAnalyzed=liveJobs?.analyzedJobs||analyzedJobs, currentAwaiting=liveJobs?.awaitingAnalysis||awaitingAnalysis;
    const known=new Set([...currentAnalyzed,...currentAwaiting].map(job=>job.id));
    const analyzed=currentAnalyzed.map(job=>({...job,stage:"analyzed" as const,source:sourceKey(alerts.find(item=>item.lead_id===job.id)?.source||new URL(job.postingUrl).hostname),leadId:job.id}));
    const awaiting=currentAwaiting.map(job=>({...job,stage:"awaiting" as const,source:sourceKey(alerts.find(item=>item.lead_id===job.id)?.source||new URL(job.postingUrl).hostname),leadId:job.id}));
    const linked=alerts.filter(job=>job.lead_id&&!known.has(job.lead_id)).map(job=>({id:`linked-${job.id}`,company:job.captured_job?.company||job.company||job.source,role:job.captured_job?.role||job.title,location:job.captured_job?.location||job.location||null,postingUrl:job.posting_url,postedDate:job.captured_job?.posted_date,firstSeenAt:job.captured_job?.first_seen_at||job.received_at,discoveryScore:job.captured_job?.discovery_score??job.preliminary_fit?.score??null,workflowStatus:job.workflow_status||"not_started",stage:"awaiting" as const,source:sourceKey(job.source),leadId:job.lead_id,alertId:job.id,analysisPrioritized:job.captured_job?.analysis_prioritized,screeningReasons:job.captured_job?.screening_reasons}));
    const capture=alerts.filter(job=>!job.lead_id).map(job=>({id:`alert-${job.id}`,company:job.company||job.source[0].toUpperCase()+job.source.slice(1),role:job.title,location:job.location||null,postingUrl:job.posting_url,firstSeenAt:job.received_at,discoveryScore:job.preliminary_fit?.score??null,workflowStatus:"needs_capture",stage:"capture" as const,source:sourceKey(job.source),leadId:null,alertId:job.id,captureMode:job.capture?.mode||"manual_required",captureReason:job.capture?.reason,captureStatus:job.capture?.status,captureServiceError:job.capture?.error,metadataFitLabel:job.preliminary_fit?.label,metadataFitBasis:job.preliminary_fit?.basis,metadataFitLimitations:job.preliminary_fit?.limitations,emailExcerpt:job.email_excerpt}));
    return [...analyzed,...awaiting,...linked,...capture];
  },[analyzedJobs,awaitingAnalysis,alerts,liveJobs]);
  const sourceCounts=useMemo(()=>jobs.reduce<Record<string,number>>((counts,job)=>({...counts,[job.source]:(counts[job.source]||0)+1}),{}),[jobs]);
  const filtered=useMemo(()=>jobs.filter(job=>{const text=`${job.company} ${job.role} ${job.location||""}`.toLowerCase(); return(!search||text.includes(search.toLowerCase()))&&(stage==="all"||workflowGroup(job)===stage)&&(source==="all"||job.source===source)&&(fit==="all"||job.stage==="analyzed"&&job.recommendation===fit);}).sort((left,right)=>{if(sort==="newest")return(right.firstSeenAt||right.postedDate||"").localeCompare(left.firstSeenAt||left.postedDate||"");if(sort==="company")return left.company.localeCompare(right.company);if(sort==="source")return left.source.localeCompare(right.source);return(right.fitScore??right.discoveryScore??-1)-(left.fitScore??left.discoveryScore??-1);}),[jobs,search,stage,source,fit,sort]);
  const selected=jobs.find(job=>job.id===selectedJobId&&job.leadId);
  async function safeCapture(job:JobRow){if(!job.alertId)return;setCapturingId(job.alertId);setCaptureError(current=>({...current,[job.alertId!]:""}));try{const response=await fetch(`http://localhost:8787/api/job-alerts/${job.alertId}/safe-capture`,{method:"POST"});const value=await response.json();if(!response.ok)throw new Error(value.error||"Safe capture failed.");await refreshAlerts();window.dispatchEvent(new Event("jobs-changed"));}catch(error){setCaptureError(current=>({...current,[job.alertId!]:error instanceof Error?error.message:"Safe capture failed."}));}finally{setCapturingId(null);}}
  return <section className="jobs-workspace" id="analysis-queue">
    <div className="section-heading"><div><p className="eyebrow">ALL JOB SOURCES</p><h2>Jobs workspace</h2></div><span>{filtered.length} of {jobs.length} jobs</span></div>
    <div className="jobs-toolbar unified">
      <input aria-label="Search jobs" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title, company, or location" />
      <select aria-label="Filter by stage" value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All workflow stages</option>{["capture","analysis","decision","strategy","materials","review_apply","submitted","closed"].map(key=><option key={key} value={key}>{workflowLabel[key]}</option>)}</select>
      <select aria-label="Filter by source" value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources ({jobs.length})</option>{["linkedin","indeed","eluta","ziprecruiter","greenhouse","lever"].map(key=><option key={key} value={key}>{sourceLabel[key]} ({sourceCounts[key]||0})</option>)}</select>
      <select aria-label="Filter by fit" value={fit} onChange={e=>setFit(e.target.value)}><option value="all">All fit decisions</option><option value="strong_apply">Strong match</option><option value="apply">Apply</option><option value="selective_apply">Stretch</option><option value="do_not_apply">Do not apply</option></select>
      <select aria-label="Sort jobs" value={sort} onChange={e=>setSort(e.target.value)}><option value="priority">Best score</option><option value="newest">Newest first</option><option value="company">Company A–Z</option><option value="source">Source</option></select>
    </div>
    <div className="jobs-list">{filtered.slice(0,visible).map(job=><article className={`job-result${job.profileStale?" stale-fit":""}${workflowIsProcessing(job.workflowStatus)?" is-processing":""}`} key={job.id}>
      <header><span className="company-avatar">{job.company.charAt(0)}</span><div><h3>{job.role}</h3><p>{job.company} · {job.location||"Location not stated"}</p><small className="job-date">{dateLabel(job)} · {sourceLabel[job.source]||job.source}</small><WorkflowActivity status={job.workflowStatus}/></div><div className="job-badges">{job.profileStale&&<span className="profile-stale">Profile updated</span>}{job.stage==="analyzed"&&<span className={`recommendation ${job.recommendation}`}>{recommendationLabel[job.recommendation||""]}</span>}{job.stage==="capture"&&<span className={`capture-mode ${job.captureMode}`}>{job.captureStatus==="safe_capture_queued"?"Safe capture queued":job.captureStatus==="safe_capturing"?"Capturing safely":job.captureStatus==="safe_capture_failed"?"Safe capture needs attention":job.captureMode==="automatic_available"?"Automatic capture available":"Manual capture required"}</span>}<span className={`workflow-badge ${workflowGroup(job)}`}>{workflowBadgeLabel(job)}</span></div></header>
      <div className={`job-result-score${job.stage==="capture"&&job.discoveryScore==null?" unavailable":""}`} title={job.metadataFitLimitations?.join(" ")}><strong>{job.stage==="analyzed"?job.fitScore:job.discoveryScore??"—"}</strong><span>{job.profileStale?"previous fit · refresh recommended":job.stage==="analyzed"?"verified fit":job.stage==="capture"&&job.discoveryScore==null?"estimate unavailable":job.stage==="capture"?"email estimate · posting not captured":"full-posting estimate · not analyzed"}</span></div>
      {job.stage==="capture"&&job.metadataFitLabel&&<p className="metadata-fit-note"><strong>{job.metadataFitLabel}.</strong> Full fit requires the complete posting.</p>}
      {job.stage==="awaiting"&&job.analysisPrioritized===false&&<p className="preliminary-screening-note"><strong>Not prioritized automatically.</strong> This is preliminary screening, not a rejection. You can still run a verified analysis.</p>}
      {job.risk&&<p className="risk"><strong>Main consideration:</strong> {job.risk}</p>}
      {job.profileStale&&<p className="stale-fit-notice">Your verified profile changed after this fit was calculated. Re-analyze to use the latest evidence.</p>}
      {job.alertId&&(captureError[job.alertId]||job.captureServiceError)&&<p className="safe-capture-error">{captureError[job.alertId]||job.captureServiceError}</p>}
      <div className="job-result-actions">{job.profileStale&&job.leadId&&<AnalyzeButton leadId={job.leadId} label="Re-analyze fit" />}{job.leadId?<button className="open-role-workflow" onClick={()=>setSelectedJobId(job.id)}>Open workflow</button>:job.captureMode==="automatic_available"?<button className="safe-capture-button" disabled={capturingId===job.alertId||["safe_capture_queued","safe_capturing"].includes(job.captureStatus||"")} title={job.captureReason} onClick={()=>safeCapture(job)}>{capturingId===job.alertId||job.captureStatus==="safe_capturing"?"Capturing safely…":job.captureStatus==="safe_capture_queued"?"Queued for safe capture":job.captureStatus==="safe_capture_failed"?"Retry safe capture":"Capture automatically"}</button>:<a className="capture-posting" title={job.captureReason} href={job.postingUrl} target="_blank" rel="noreferrer">Open and capture posting</a>}<a href={job.postingUrl} target="_blank" rel="noreferrer">View posting</a></div>
    </article>)}</div>
    {visible<filtered.length&&<button className="load-more" onClick={()=>setVisible(count=>count+15)}>Show 15 more</button>}
    {selected?.leadId&&<div className="workflow-drawer-backdrop" onClick={()=>setSelectedJobId(null)}><aside className="workflow-drawer" onClick={event=>event.stopPropagation()}><JobWorkflowPanel job={{...selected,id:selected.leadId,stage:selected.stage==="analyzed"?"analyzed":"awaiting"}} onClose={()=>setSelectedJobId(null)} /></aside></div>}
  </section>;
}
