"use client";

import { useState } from "react";
import { AnalyzeButton } from "./AnalyzeButton";
import { DecisionButtons } from "./DecisionButtons";

type Job = { id: string; company: string; role: string; postingUrl: string; stage: "analyzed" | "awaiting" };
type Posting = { company: string; title: string; description: string; location: string; workplace_type: string; employment_type: string; posted_date?: string | null; captured_at: string; source: string };
type Prep = { most_likely_concern: string; response_strategy: string; verify_before_interview: string[]; questions_to_ask: string[]; stories: Array<{ story_id: string; core_message: string; why_it_fits: string; sample_questions: string[]; evidence_id: string }> };

export function JobWorkflowPanel({ job, onClose }: { job: Job; onClose: () => void }) {
  const [posting, setPosting] = useState<Posting | null>(null), [showPosting, setShowPosting] = useState(false), [postingMessage, setPostingMessage] = useState("");
  const [prep, setPrep] = useState<Prep | null>(null), [showPrep, setShowPrep] = useState(false), [prepMessage, setPrepMessage] = useState("");
  async function archive() { setShowPosting((value) => !value); if (posting) return; try { const response = await fetch(`http://localhost:8787/api/jobs/${job.id}/job-posting`); const value = await response.json(); if (!response.ok) throw new Error(value.error); setPosting(value); } catch (error) { setPostingMessage(error instanceof Error ? error.message : "Saved posting unavailable."); } }
  async function interview() { setShowPrep((value) => !value); if (prep) return; setPrepMessage("Preparing from verified evidence…"); try { let response = await fetch(`http://localhost:8787/api/jobs/${job.id}/interview-preparation`); if (response.status === 404) response = await fetch(`http://localhost:8787/api/jobs/${job.id}/interview-preparation`, { method: "POST" }); const value = await response.json(); if (!response.ok) throw new Error(value.error); setPrep(value); setPrepMessage(""); } catch (error) { setPrepMessage(error instanceof Error ? error.message : "Interview preparation unavailable."); } }
  return <section className="job-workflow-detail active-role-workflow"><header><div><span>APPLICATION WORKSPACE</span><h3>{job.role}</h3><p>{job.company} · {job.stage === "analyzed" ? "Analyzed" : "Ready to analyze"}</p></div><div><button onClick={archive}>{showPosting ? "Hide saved posting" : "View saved posting"}</button>{job.stage === "analyzed" && <button onClick={interview}>{showPrep ? "Hide interview prep" : "Interview prep"}</button>}<a href={job.postingUrl} target="_blank" rel="noreferrer">Original link</a><button onClick={onClose}>Close</button></div></header>{showPosting && <aside className="saved-posting">{posting ? <><header><div><span>PERMANENT JOB ARCHIVE</span><strong>{posting.company} · {posting.title}</strong></div><small>Captured {posting.captured_at.slice(0, 10)} · {posting.source}</small></header><dl><div><dt>Location</dt><dd>{posting.location || "Not provided"}</dd></div><div><dt>Work arrangement</dt><dd>{posting.workplace_type.replaceAll("_", " ")}</dd></div><div><dt>Employment</dt><dd>{posting.employment_type.replaceAll("_", " ")}</dd></div><div><dt>Posted</dt><dd>{posting.posted_date || "Not provided"}</dd></div></dl><details open><summary>Full saved description</summary><div className="saved-description">{posting.description}</div></details></> : <p>{postingMessage || "Loading saved posting…"}</p>}</aside>}{showPrep && <section className="interview-preparation">{prep ? <><div className="interview-concern"><strong>Most likely concern</strong><p>{prep.most_likely_concern}</p><span>{prep.response_strategy}</span></div><div className="interview-stories">{prep.stories.map((story) => <article key={story.story_id}><strong>{story.core_message}</strong><span>{story.why_it_fits}</span><small>Evidence: {story.evidence_id}</small><details><summary>Likely questions</summary><ul>{story.sample_questions.map((question) => <li key={question}>{question}</li>)}</ul></details></article>)}</div><div className="interview-lists"><section><strong>Verify before interview</strong><ul>{prep.verify_before_interview.map((item) => <li key={item}>{item}</li>)}</ul></section><section><strong>Questions to ask</strong><ul>{prep.questions_to_ask.map((item) => <li key={item}>{item}</li>)}</ul></section></div></> : <p>{prepMessage}</p>}</section>}<main>{job.stage === "analyzed" ? <DecisionButtons leadId={job.id} /> : <AnalyzeButton leadId={job.id} />}</main></section>;
}
