"use client";

import { useEffect, useState } from "react";

type ProfileRun = { id: string; status: string; files: string[]; after_version?: string | null; error?: string | null; summary?: { files_processed: string[]; files_skipped: string[]; changes: string[]; warnings: string[]; profile_version: string } | null };
type ProfileStatus = { profile_version: string; latest_run?: ProfileRun | null };

export function ProfileManager() {
  const [status, setStatus] = useState<ProfileStatus | null>(null), [files, setFiles] = useState<File[]>([]), [instructions, setInstructions] = useState(""), [run, setRun] = useState<ProfileRun | null>(null), [message, setMessage] = useState("");
  const working = run && ["requested", "running"].includes(run.status);
  useEffect(() => { fetch("http://localhost:8787/api/profile").then((response) => response.ok ? response.json() : null).then((value) => { if (value) { setStatus(value); if (value.latest_run) setRun(value.latest_run); } }).catch(() => undefined); }, []);
  useEffect(() => { if (!working || !run) return; const timer = window.setInterval(async () => { const response = await fetch(`http://localhost:8787/api/profile/runs/${run.id}`); if (!response.ok) return; const next = await response.json(); setRun(next); if (next.status === "completed") { setMessage("Profile rebuilt. Existing fit analyses are now marked for review."); setFiles([]); setStatus((current) => current ? { ...current, profile_version: next.after_version, latest_run: next } : current); window.dispatchEvent(new Event("jobs-changed")); } if (next.status === "failed") setMessage(next.error || "Profile rebuild failed."); }, 1500); return () => window.clearInterval(timer); }, [working, run]);
  async function rebuild() { const body = new FormData(); files.forEach((file) => body.append("resumes", file)); body.append("instructions", instructions); setMessage("Uploading resumes and starting verified profile rebuild…"); try { const response = await fetch("http://localhost:8787/api/profile/rebuild", { method: "POST", body }); const value = await response.json(); if (!response.ok) throw new Error(value.error); setRun(value); setMessage("Profile rebuild queued. You can continue using the app."); } catch (error) { setMessage(error instanceof TypeError ? "Profile service is offline." : error instanceof Error ? error.message : "Profile rebuild could not start."); } }
  const latest = run || status?.latest_run;
  return <section className="profile-manager" id="profile"><div className="section-heading"><div><p className="eyebrow">VERIFIED CAREER PROFILE</p><h2>Rebuild profile from resumes</h2></div><span>Version {status?.profile_version || "loading"}</span></div><p>Upload up to 10 PDF resumes. The agent reconciles supported facts into career, evidence, skills, and technologies while preserving protected contacts.</p><input aria-label="Resume PDFs" type="file" accept="application/pdf,.pdf" multiple onChange={(event) => setFiles(Array.from(event.target.files || []))} /><textarea aria-label="Profile rebuild instructions" rows={3} value={instructions} onChange={(event) => setInstructions(event.target.value)} placeholder="Optional rules, e.g. omit a role, preserve a title, or consolidate older work." /><div className="profile-rebuild-actions"><span>{files.length ? `${files.length} PDF${files.length === 1 ? "" : "s"} selected` : "No resumes selected"}</span><button disabled={Boolean(working) || files.length < 1 || files.length > 10} onClick={rebuild}>{working ? "Rebuilding profile…" : "Upload and rebuild profile"}</button></div>{message && <small role="status">{message}</small>}{latest?.summary && <details className="profile-rebuild-summary"><summary>Latest rebuild details</summary><strong>{latest.summary.files_processed.length} resume(s) processed</strong>{latest.summary.files_skipped.length > 0 && <ul>{latest.summary.files_skipped.map((item) => <li key={item}>{item}</li>)}</ul>}{latest.summary.changes.length > 0 && <ul>{latest.summary.changes.map((item) => <li key={item}>{item}</li>)}</ul>}{latest.summary.warnings.length > 0 && <ul>{latest.summary.warnings.map((item) => <li key={item}>{item}</li>)}</ul>}</details>}</section>;
}
