"use client";

import { useEffect, useState } from "react";

type Source = { id: string; company: string; platform: string; enabled: boolean };
type Settings = { roles: string[]; locations: string[]; frequency: string; sources: Source[] };

export function SearchSettings() {
  const [open, setOpen] = useState(false), [settings, setSettings] = useState<Settings | null>(null);
  const [message, setMessage] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { if (!open || settings) return; fetch("http://localhost:8787/api/search-settings").then(async (response) => { const value = await response.json(); if (!response.ok) throw new Error(value.error); return value; }).then(setSettings).catch(() => setMessage("Start the local workflow service to edit search settings.")); }, [open, settings]);
  async function save() { if (!settings) return; setSaving(true); setMessage(""); try { const response = await fetch("http://localhost:8787/api/search-settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ roles: settings.roles, locations: settings.locations, frequency: settings.frequency, enabled_source_ids: settings.sources.filter((source) => source.enabled).map((source) => source.id) }) }); const value = await response.json(); if (!response.ok) throw new Error(value.error || "Settings could not be saved."); setSettings(value); setMessage("Saved. These preferences will be used for the next search."); } catch (error) { setMessage(error instanceof Error ? error.message : "Settings could not be saved."); } finally { setSaving(false); } }
  const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
  return <div className="search-settings-control"><button className="settings-button" type="button" onClick={() => setOpen((value) => !value)}>{open ? "Close settings" : "Search settings"}</button>{open && <section className="settings-panel" aria-label="Job search settings"><div className="section-heading"><div><p className="eyebrow">DISCOVERY PREFERENCES</p><h2>What should I search for?</h2></div></div>{!settings ? <p className="settings-message" role="status">{message || "Loading your preferences…"}</p> : <><div className="settings-grid"><label><strong>Target roles</strong><span>One title per line, highest priority first.</span><textarea value={settings.roles.join("\n")} onChange={(event) => setSettings({ ...settings, roles: lines(event.target.value) })} rows={7} /></label><label><strong>Preferred locations</strong><span>Include remote and local arrangements you want.</span><textarea value={settings.locations.join("\n")} onChange={(event) => setSettings({ ...settings, locations: lines(event.target.value) })} rows={7} /></label></div><fieldset><legend>Employer job boards</legend><div className="source-options">{settings.sources.map((source) => <label key={source.id}><input type="checkbox" checked={source.enabled} onChange={(event) => setSettings({ ...settings, sources: settings.sources.map((item) => item.id === source.id ? { ...item, enabled: event.target.checked } : item) })} /><span><strong>{source.company}</strong><small>{source.platform}</small></span></label>)}</div></fieldset><label className="frequency-field"><strong>Search frequency</strong><select value={settings.frequency} onChange={(event) => setSettings({ ...settings, frequency: event.target.value })}><option value="manual">Only when I click Find new jobs</option><option value="daily">Daily while the app is running</option><option value="weekly">Weekly while the app is running</option></select></label><div className="settings-footer"><p role="status">{message}</p><button type="button" onClick={save} disabled={saving}>{saving ? "Saving…" : "Save search settings"}</button></div></>}</section>}</div>;
}
